# vim: ft=dosini
[Metadata]
Name=Catppuccin
Version=0.2
Author=lonerOrz
Description=Catppuccin Color Theme (MD3 template)
ScaleWithDPI=True
[InputPanel]
# 字体
Font=Sans 13
# 非选中候选字颜色
NormalColor=#26A589
# 选中候选字颜色
HighlightCandidateColor=#1E9177
# 高亮前景颜色(输入字符颜色)
HighlightColor=#26A589
# 输入字符背景颜色
# Surface 0
HighlightBackgroundColor=#0E1512
Spacing=3
[InputPanel/TextMargin]
# 候选字对左边距
Left=10
# 候选字对右边距
Right=10
# 候选字向上边距
Top=6
# 候选字向下边距
Bottom=6
[InputPanel/Background]
# Surface 0
Color=#0E1512
# Surface 0
BorderColor=#0E1512
BorderWidth=2
[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2
[InputPanel/Highlight]
# Surface 0
Color=#0E1512
[InputPanel/Highlight/Margin]
# 高亮区域左边距
Left=10
# 高亮区域右边距
Right=10
# 高亮区域上边距
Top=7
# 高亮区域下边距
Bottom=7
[Menu]
Font=Sans 10
# Text
NormalColor=#FFFFFF
Spacing=3
[Menu/Background]
# Surface 0
Color=#0E1512
[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2
[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2
[Menu/Highlight]
# Pink
Color=#167A63
[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5
[Menu/Separator]
# Base
Color=#3C4A44
[Menu/CheckBox]
Image=radio.png
[Menu/SubMenu]
Image=arrow.png
[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
